config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :comments

  resources :items do 
    collection do 
      get :search
			get :my_bar
			get :my_wish
    end
		member do 
			get :edit_labels
			put :add_label
			put :remove_label
		end
		resources :comments
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :ingredients

  resources :recipes do 
		collection do 
			get :available
      get :labels
		end
      
		member do 
			get :edit_labels
			put :add_label
			put :remove_label
      get :fork
		end

    resources :ingredients
		resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :markable, polymorphic: true
	belongs_to :user


	CONTEXTS = ["bar_item", "wish_item"]
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: %i[ show edit update destroy ]

  # GET /marks or /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1 or /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks or /marks.json
  def create
		@markable = params[:markable_type].constantize.find(params[:markable_id])
    @mark = Mark.new
		if Mark::CONTEXTS.include? params[:context]
			@mark.context = params[:context]
		end
		@mark.markable = @markable
		@mark.user = current_user

    respond_to do |format|
      if @mark.save
        format.html { redirect_back fallback_location: @markable, notice: "Mark was successfully created." }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1 or /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to mark_url(@mark), notice: "Mark was successfully updated." }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1 or /marks/1.json
  def destroy
    @mark.destroy

    respond_to do |format|
      format.html { redirect_back fallback_location: @mark.markable, notice: "Mark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mark_params
      params.require(:mark).permit(:context)
    end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.erb
<%= simple_form_for(@mark) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/marks/_mark.html.erb
<div id="<%= dom_id mark %>">
</div>

app/views/marks/edit.html.erb
<h1>Editing mark</h1>

<%= render "form", mark: @mark %>

<br>

<div>
  <%= link_to "Show this mark", @mark %> |
  <%= link_to "Back to marks", marks_path %>
</div>

app/views/marks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Marks</h1>

<div id="marks">
  <% @marks.each do |mark| %>
    <%= render mark %>
    <p>
      <%= link_to "Show this mark", mark %>
    </p>
  <% end %>
</div>

<%= link_to "New mark", new_mark_path %>

app/views/marks/new.html.erb
<h1>New mark</h1>

<%= render "form", mark: @mark %>

<br>

<div>
  <%= link_to "Back to marks", marks_path %>
</div>

app/views/marks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mark %>

<div>
  <%= link_to "Edit this mark", edit_mark_path(@mark) %> |
  <%= link_to "Back to marks", marks_path %>

  <%= button_to "Destroy this mark", @mark, method: :delete %>
</div>