config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :comments

  resources :items do 
    collection do 
      get :search
			get :my_bar
			get :my_wish
    end
		member do 
			get :edit_labels
			put :add_label
			put :remove_label
		end
		resources :comments
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :ingredients

  resources :recipes do 
		collection do 
			get :available
      get :labels
		end
      
		member do 
			get :edit_labels
			put :add_label
			put :remove_label
      get :fork
		end

    resources :ingredients
		resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

	scope :recent, -> { order "created_at DESC" }

	belongs_to :user

	validates :comment, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
		@commentable = params[:commentable_type].constantize.find(params[:commentable_id])
    @comment = @commentable.comments.new(comment_params)
		@comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_back fallback_location: @commentable, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="py-4 border-b">
  <div class="flex w-full text-sm text-gray-500">
    <span class=""><%= comment.user %></span>
    <span class="ml-auto text-gray-500"><%= comment.created_at.to_date %></span>
  </div>
  <div class="mt-2">
    <%= simple_format comment.comment %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@commentable, comment] do |f| %>
  <div class="mb-4">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.input :comment, label: false, input_html: {data: {controller: "textarea-autogrow"}} %>

    <div>
      <%= hidden_field_tag :commentable_type, @commentable.try(:class) %>
      <%= hidden_field_tag :commentable_id, @commentable.try(:id) %>
      <%= f.submit "Submit", class: "btn btn--primary" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>