config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :comments

  resources :items do 
    collection do 
      get :search
			get :my_bar
			get :my_wish
    end
		member do 
			get :edit_labels
			put :add_label
			put :remove_label
		end
		resources :comments
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :ingredients

  resources :recipes do 
		collection do 
			get :available
      get :labels
		end
      
		member do 
			get :edit_labels
			put :add_label
			put :remove_label
      get :fork
		end

    resources :ingredients
		resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
	belongs_to :item, foreign_key: :name, optional: true

  validates :name, presence: true
  validates :quantity, presence: true
  validates :unit, presence: true

  scope :ordered, -> { order id: :asc }

  UNITS = [:ml, :cl, :oz, :shot, :part, :dash, :spoon, :barspoon, :tablespoon]

	def name= str
		return if str.blank?
		write_attribute :name, str.to_s.strip
	end

	before_validation :save_item
	def save_item
		Item.find_or_create_by name: self.name, user: self.recipe.user
	end

	def f_quantity
		if self.quantity.to_i == 0
			nil
		elsif self.quantity.to_i == self.quantity
			self.quantity.to_i
		else
			self.quantity
		end
	end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]
  before_action :set_recipe, only: %i[ new create ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
    @recipe = @ingredient.recipe
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = @recipe.ingredients.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    @recipe = @ingredient.recipe

    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient.recipe, notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def set_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      # params.fetch(:ingredient, {})
      params.require(:ingredient).permit(:name, :quantity, :unit)
    end
end

app/views/ingredients/_form.html.erb
<%= simple_form_for [@recipe, ingredient], html: { class: "recipe form" } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="flex items-center">
    <div data-controller="autocomplete" data-autocomplete-url-value="/items/search">
      <%= f.input :name, label: false, input_html: {placeholder: "Item Name", class: "w-auto", autofocus: true, data: {autocomplete_target: 'input'} } %>
      <ul class="list-group absolute" data-autocomplete-target="results"></ul>
    </div>

    <%= f.input :quantity, label: false, input_html: {placeholder: "Quantity"}, wrapper_html: { class: "" } %>
    <%= f.input :unit, collection: Ingredient::UNITS, label: false, input_html: {placeholder: "unit"}, wrapper_html: { class: "" } %>

    <%= f.submit class: "btn btn--primary" %>
    <%= link_to "Cancel", @recipe || ingredient.recipe, class: "btn btn--light" %>
  </div>
<% end%>

app/views/ingredients/_ingredient.html.erb
<div class="flex items-center my-1">
	<span class="mr-2 w-24">
		<%= ingredient.f_quantity %>
		<%= ingredient.unit %>
	</span>
	<span class="mr-2">
		<%= link_to ingredient.name, items_path(q: ingredient.name) %>

		<% if @my_bar_items.include? ingredient.name %>
			<i class="fa-solid fa-check"></i>
		<% end %>
	</span>
</div>

app/views/ingredients/create.turbo_stream.erb
<%= turbo_stream.update "#{dom_id @recipe}_#{dom_id Ingredient.new}", "" %>
<%= turbo_stream.append "#{dom_id @ingredient.recipe}_ingredients", @ingredient %>

app/views/ingredients/destroy.turbo_stream.erb
<%= turbo_stream.remove @ingredient %>

app/views/ingredients/edit.html.erb
<%= link_to sanitize("&larr; Back to recipe"), @ingredient.recipe %>

<div class="header">
  <h1>Edit Ingredient</h1>
</div>

<%= turbo_frame_tag @ingredient do %>
  <%= render "form", ingredient: @ingredient %>
<% end %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<div id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <%= render ingredient %>
    <p>
      <%= link_to "Show this ingredient", ingredient %>
    </p>
  <% end %>
</div>

<%= link_to "New ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<%= link_to sanitize("&larr; Back to recipe"), @recipe %>

<div class="header">
  <h1>New Recipe</h1>
</div>


<%= turbo_frame_tag "#{dom_id @recipe}_#{dom_id Ingredient.new}" do %>
  <%= render "form", ingredient: @ingredient %>
<% end %>

app/views/ingredients/show.html.erb
<%= render @ingredient %>

<div>
  <%= link_to "Edit this ingredient", edit_ingredient_path(@ingredient) %> |
  <%= link_to "Back to ingredients", ingredients_path %>

  <%= button_to "Destroy this ingredient", @ingredient, method: :delete %>
</div>